import { Route } from './types/Route';

const METHODS_WITH_BODY = new Set(['POST', 'PUT', 'PATCH']);

export function generateHttpRequests(routes: Route[], baseUrl: string): string {
  const parameters = collectPathParameters(routes);
  const lines = [
    '# Generated by RouteLens',
    '',
    `@baseUrl = ${baseUrl.trim().replace(/\/+$/, '')}`,
  ];

  for (const parameter of parameters) {
    lines.push(`@${parameter} = 1`);
  }

  lines.push('');

  for (const route of sortRoutes(routes)) {
    const resource = route.resource ?? 'root';
    const requestPath = replacePathParameters(route.path);

    lines.push(`### ${route.method} ${route.path}`);
    lines.push(`# Resource: ${resource}`);
    lines.push(`${route.method} {{baseUrl}}${requestPath}`);

    if (METHODS_WITH_BODY.has(route.method)) {
      lines.push(
        'Content-Type: application/json',
        '',
        '{',
        '  "example": "value"',
        '}'
      );
    }

    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function collectPathParameters(routes: Route[]): string[] {
  const parameters = new Set<string>();
  const pattern = /\{([^}]+)\}/g;

  for (const route of routes) {
    for (const match of route.path.matchAll(pattern)) {
      parameters.add(match[1]);
    }
  }

  return [...parameters].sort((left, right) => left.localeCompare(right));
}

function replacePathParameters(routePath: string): string {
  return routePath.replace(/\{([^}]+)\}/g, '{{$1}}');
}

function sortRoutes(routes: Route[]): Route[] {
  return [...routes].sort((left, right) => {
    const resourceComparison = (left.resource ?? '').localeCompare(right.resource ?? '');

    if (resourceComparison !== 0) {
      return resourceComparison;
    }

    const pathComparison = left.path.localeCompare(right.path);

    return pathComparison !== 0 ? pathComparison : left.method.localeCompare(right.method);
  });
}
