import { Route } from './types/Route';
import { buildRouteUrl } from './urlBuilder';

export function generateMarkdown(
  routes: Route[],
  getFileLabel: (filePath: string) => string,
  baseUrl: string
): string {
  const lines = [
    '# API Routes',
    '',
    '> Generated by RouteLens.',
    '',
    `Base URL: \`${baseUrl}\``,
    '',
  ];
  const routesByFile = groupRoutesByFile(routes);

  for (const [filePath, fileRoutes] of routesByFile) {
    lines.push(`## ${getFileLabel(filePath)}`, '');
    const routesByResource = groupRoutesByResource(fileRoutes);

    for (const [resource, resourceRoutes] of routesByResource) {
      lines.push(`### ${resource}`, '');

      for (const route of resourceRoutes) {
        lines.push(`#### ${route.method} \`${route.path}\``, '');
        lines.push(`- URL: \`${buildRouteUrl(baseUrl, route.path)}\``);

        if (route.language) {
          lines.push(`- Language: \`${route.language}\``);
        }

        if (route.framework) {
          lines.push(`- Framework: \`${route.framework}\``);
        }

        if (route.handler) {
          lines.push(`- Handler: \`${route.handler}\``);
        }

        lines.push(`- Source: line ${route.line}`, '');
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

function groupRoutesByResource(routes: Route[]): Array<[string, Route[]]> {
  const routesByResource = new Map<string, Route[]>();

  for (const route of routes) {
    const resource = route.resource ?? 'root';
    const resourceRoutes = routesByResource.get(resource) ?? [];

    resourceRoutes.push(route);
    routesByResource.set(resource, resourceRoutes);
  }

  return [...routesByResource.entries()]
    .sort(([leftResource], [rightResource]) => leftResource.localeCompare(rightResource));
}

function groupRoutesByFile(routes: Route[]): Array<[string, Route[]]> {
  const routesByFile = new Map<string, Route[]>();

  for (const route of routes) {
    const fileRoutes = routesByFile.get(route.filePath) ?? [];

    fileRoutes.push(route);
    routesByFile.set(route.filePath, fileRoutes);
  }

  return [...routesByFile.entries()]
    .map(([filePath, fileRoutes]) => [
      filePath,
      [...fileRoutes].sort((left, right) => left.line - right.line),
    ] as [string, Route[]])
    .sort(([leftPath], [rightPath]) => leftPath.localeCompare(rightPath));
}
