import { Route } from './types/Route';

export function generateMarkdown(
  routes: Route[],
  getFileLabel: (filePath: string) => string
): string {
  const lines = [
    '# API Routes',
    '',
    '> Generated by RouteLens.',
    '',
  ];
  const routesByFile = groupRoutesByFile(routes);

  for (const [filePath, fileRoutes] of routesByFile) {
    lines.push(`## ${getFileLabel(filePath)}`, '');

    for (const route of fileRoutes) {
      lines.push(`### ${route.method} \`${route.path}\``, '');

      if (route.handler) {
        lines.push(`- Handler: \`${route.handler}\``);
      }

      lines.push(`- Source: line ${route.line}`, '');
    }
  }

  return `${lines.join('\n')}\n`;
}

function groupRoutesByFile(routes: Route[]): Array<[string, Route[]]> {
  const routesByFile = new Map<string, Route[]>();

  for (const route of routes) {
    const fileRoutes = routesByFile.get(route.filePath) ?? [];

    fileRoutes.push(route);
    routesByFile.set(route.filePath, fileRoutes);
  }

  return [...routesByFile.entries()]
    .map(([filePath, fileRoutes]) => [
      filePath,
      [...fileRoutes].sort((left, right) => left.line - right.line),
    ] as [string, Route[]])
    .sort(([leftPath], [rightPath]) => leftPath.localeCompare(rightPath));
}
